version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=your-strong-secret
      - USER_SERVICE_URL=http://user-service:8000
    networks:
      - ticket-network

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./user.db
    networks:
      - ticket-network
    volumes:
      - user-data:/app/data

  ticket-service:
    build: ./ticket-service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-strong-secret
      - USER_SERVICE_URL=http://user-service:8000
    networks:
      - ticket-network
    volumes:
      - ticket-data:/app/data

networks:
  ticket-network:
    driver: bridge

volumes:
  user-data:
  ticket-data: