version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=your-strong-secret
    networks:
      - ticket-network
    volumes:
      - auth-data:/app/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./user.db
      - AUTH_SERVICE_URL=http://auth-service:8000/validate
    networks:
      - ticket-network
    volumes:
      - user-data:/app/data

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=sqlite:///./ticket.db
      - AUTH_SERVICE_URL=http://auth-service:8000/validate
    networks:
      - ticket-network
    volumes:
      - ticket-data:/app/data

networks:
  ticket-network:
    driver: bridge

volumes:
  auth-data:
  user-data:
  ticket-data:
